import numpy as np
import time

import rclpy
from rclpy.node import Node
from casadi import vertcat
from omni_msgs.msg import HIDState, HIDFeedback

from dynamic_models.utility import create_dynamic_model
from utility_functions.path_utilities import ReferencePath

class FakeHardware(Node):
    def __init__(self):
        super().__init__('fake_system')

        self.mass = 1
        self.damping_factor = 0.1
        self.stiffness = 1

        self.get_params()
        self.initialize_publisher_and_subscriber()
        self.initalize_system_dynamics()
        self.timer = self.create_timer(self.system_period, self.system_state_callback)
        self.get_logger().info("Fake System Node has been initialized")



    def get_params(self):
        #self.declare_parameter('system_parameters.x0', rclpy.Parameter.Type.DOUBLE_ARRAY)
        self.declare_parameter('system_parameters.system_period', rclpy.Parameter.Type.DOUBLE)
        self.declare_parameter('system_parameters.state_space_names', rclpy.Parameter.Type.STRING_ARRAY)
        self.declare_parameter('system_parameters.system_type', rclpy.Parameter.Type.INTEGER)
        self.declare_parameter('system_parameters.system_parameters', rclpy.Parameter.Type.DOUBLE_ARRAY)
        self.declare_parameter('human_control', rclpy.Parameter.Type.BOOL)
        self.declare_parameter('reference_tracking.trajectory_type', rclpy.Parameter.Type.INTEGER)
        self.declare_parameter('reference_tracking.trajectory_scaling_factor', rclpy.Parameter.Type.DOUBLE)
        

        # define parent class variables 
        #self.initial_state = self.get_parameter('system_parameters.x0').get_parameter_value().double_array_value
        self.system_period = self.get_parameter('system_parameters.system_period').get_parameter_value().double_value
        self.state_space_names = self.get_parameter('system_parameters.state_space_names').get_parameter_value().string_array_value
        self.system_type = self.get_parameter('system_parameters.system_type').get_parameter_value().integer_value
        self.system_parameters = self.get_parameter('system_parameters.system_parameters').get_parameter_value().double_array_value
        self.human_control = self.get_parameter('human_control').get_parameter_value().bool_value
        self.trajectory_type = self.get_parameter('reference_tracking.trajectory_type').get_parameter_value().integer_value
        self.traj_scaling = self.get_parameter('reference_tracking.trajectory_scaling_factor').get_parameter_value().double_value


    def initialize_publisher_and_subscriber(self):
        self.force_feedback_subscriber = self.create_subscription(HIDFeedback, '/master/feedback', self.read_force_feedback, 1)
        if self.human_control:
            self.force_feedback_subscriber = self.create_subscription(HIDFeedback, '/master/feedback_human', self.read_force_feedback_human, 1)

        self.system_state_publisher = self.create_publisher(HIDState, '/master/state', 1)


    def initalize_system_dynamics(self):
        '''
        Initalize the robot dynamics class. This serves as a place holder for the actual system dynamics.
        Use the methods defined in dynamic_models.utility to create the system dynamics. System type may be changed in the yamal file.
        '''
        self.robot_dynamics_obj = create_dynamic_model(self.system_type, self.system_parameters, self.state_space_names[0:6], self.state_space_names[6:9])
        
        if not self.human_control:
            dx, x, u, A, B = self.robot_dynamics_obj.define_system_dynamics()
            self.system_integrator = self.robot_dynamics_obj.create_system_integrator(x, u, dx, self.system_period)

        else:
            dx, x, u, u_h, A, B = self.robot_dynamics_obj.define_system_dynamics_plus_human()
            self.system_integrator = self.robot_dynamics_obj.create_system_integrator_plus_human(x, u, u_h, dx, self.system_period)

            self.force_input_human = np.zeros((3,1), dtype=float)

        self.force_input = np.zeros((3,1), dtype=float)

        self.get_logger().info(f"System Dynamics: A = {A}, B = {B}")

        self.get_logger().info(f"Human_control?: {self.human_control}")
        

        path_obj = ReferencePath(num_points=100, trajectory_type=self.trajectory_type, trajectory_scaling= self.traj_scaling)
        initial_position = path_obj.ref_path[:,0]
        self.get_logger().info(f"Initial Position: {initial_position}")
        initial_state = np.vstack((initial_position.reshape(3,1), np.zeros((3,1), dtype=float)))
        self.current_state = initial_state


    def read_force_feedback(self, msg):
        """
        Read the force feedback generated by the control Node. This is the input to the modeled system.
        """
        self.force_input = np.array([msg.desired_force.x, msg.desired_force.y, msg.desired_force.z])
    
    def read_force_feedback_human(self, msg):
        """
        Read the force feedback generated by the human control Node. This is the input to the modeled system.
        """
        self.force_input_human = np.array([msg.desired_force.x, msg.desired_force.y, msg.desired_force.z])
        


    def system_state_callback(self):
        """
        Calculates the new response of the modeled system based on the current input and the dynamic model. Publish the calculated response
        to the appropriate topic.
        """
        # Calculate the system response 
        if not self.human_control:
            Ik = self.system_integrator(x0=self.current_state, p=self.force_input)
            x_next = Ik['xf'].full().reshape(-1,)
        else:
            Ik = self.system_integrator(x0=self.current_state, p=vertcat(self.force_input, self.force_input_human))
            x_next = Ik['xf'].full().reshape(-1,)

        msg = HIDState()
        msg.pose.position.x = x_next[0]   
        msg.pose.position.y = x_next[1]
        msg.pose.position.z = x_next[2]
        msg.velocity.x = x_next[3]     
        msg.velocity.y = x_next[4]
        msg.velocity.z = x_next[5]

        self.system_state_publisher.publish(msg)

        self.current_state = x_next.copy()


def main(args=None):
    rclpy.init(args=args)
    node = FakeHardware()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


    
        






